name = autoRhiWgvk
summary = RHI
outType = exe
version = 1.0
srcDirs = rhi/, example/, webgpu/,openGL/, vulkan/, spirv/
excludeSrc = .*(spirv_reflect.c|volk.c).*
depends = glslang 16, wgvk 1.0, glfw 3.3.8, glew 2.2.0
incDirs = ./
defines = SUPPORT_GLSL,__WGVK__,USE_WEBGPU,USE_VULKAN,USE_OPENGL
msvc.extConfigs.cppflags = /std:c++20 /experimental:c11atomics
win32.extLibs = OpenGL32.lib,GLU32.lib,XInput.lib,Winmm.lib,kernel32.lib,user32.lib,gdi32.lib,winspool.lib,comdlg32.lib,advapi32.lib,shell32.lib,ole32.lib,oleaut32.lib,uuid.lib,odbc32.lib,odbccp32.lib,ws2_32.lib,winmm.lib,wldap32.lib
