name = autoRhi
summary = RHI
outType = lib
version = 1.0
srcDirs = rhi/, openGL/, vulkan/, spirv/, vulkan/external/
depends = glfw 3.3.8, glslang 16, glew 2.2.0
incDirs = ./,vulkan/
defines = SUPPORT_GLSL,USE_VULKAN,USE_OPENGL
extIncDirs = 
extLibs = 
msvc.extConfigs.cppflags = /std:c++20 /experimental:c11atomics
